---
settings:
  name: BlueXP workload factory
  platform: cloud
  search: workload-setup-admin,workload-fsx-ontap,workload-databases,workload-vmware,workload-genai,workload-builders,workload-relnotes
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: false
    harmony_enabled: false
    lipi_enabled: true
  langs: zh-tw,us-en,de-de,es-es,fr-fr,it-it,pt-br,ja-jp,ko-kr,zh-cn
sidebar:
  entries:
  - title: 所有工作負載原廠文件
    url: "/index.html"
