= 追蹤及監控作業
:allow-uri-read: 


[role="lead"]
使用NetApp Workload Factory 中的 Tracker 監控和追蹤工作負載操作的執行情況並監控任務進度。

.關於這項工作
NetApp Workload Factory 提供監控功能 Tracker，因此您可以監控和追蹤工作負載操作的進度和狀態、查看操作任務和子任務的詳細資訊以及診斷任何問題或故障。

Tracker 中有幾個動作可供使用。您可以依時間範圍（過去 24 小時， 7 天， 14 天或 30 天），工作負載，狀態和使用者來篩選工作；使用搜尋功能尋找工作；並將工作表下載為 CSV 檔案。您可以隨時重新整理 Tracker ，快速重試失敗的作業或編輯失敗作業的參數，然後再試一次。

Tracker 支援兩種監控層級，視作業而定。每項工作（例如檔案系統部署）都會顯示工作說明，狀態，開始時間，工作持續時間，使用者，區域， Proxy 資源，工作 ID 及所有相關的子工作。您可以檢視 API 回應，瞭解作業期間發生的情況。

以範例追蹤工作層級::
+
--
* 層級 1 （工作）：追蹤檔案系統部署。
* 層級 2 （子工作）：追蹤與檔案系統部署相關的子工作。


--
作業狀態:: Tracker 中的作業狀態如下： _ 進行中 _ ， _ 成功 _ 及 _ 失敗 _ 。
+
--
操作頻率:: 作業頻率是根據工作類型和工作排程而定。


--
事件保留:: 事件會保留在使用者介面上 30 天。




== 追蹤及監控作業

使用 Tracker 追蹤和監控 Workload Factory 控制台中的操作。

.步驟
. 使用其中一項登link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["主控台體驗"^]入。
. 從工作量選單中，選擇*管理*，然後選擇*追蹤器*。
. 在 Tracker 中，使用篩選器或搜尋來縮小工作結果範圍。您也可以下載工作報告。




== 檢視 API 要求

在 Codebox 中檢視 Tracker 工作的 API 要求。

.步驟
. 在 Tracker 中，選取工作。
. 選擇操作選單，然後選擇*查看 API 請求*。




== 重試失敗的作業

在 Tracker 中重試失敗的作業。您也可以複製失敗作業的錯誤訊息。


NOTE: 您最多可以重試 10 次失敗的作業。

.步驟
. 在 Tracker 中，選取失敗的作業。
. 選擇操作選單，然後選擇*重試*。


.結果
作業將重新啟動。



== 編輯並重試失敗的作業

編輯失敗作業的參數，然後在 Tracker 外重試作業。

.步驟
. 在 Tracker 中，選取失敗的作業。
. 選擇操作選單，然後選擇*編輯並重試*。
+
系統會將您重新導向至作業頁面，您可以在其中編輯參數，然後重試作業。



.結果
作業將重新啟動。前往 Tracker 以檢視作業狀態。
